services:

  web:
    build: .
    container_name: cloud_optimizer_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    restart: always

  worker:
    build: .
    container_name: cloud_optimizer_worker
    command: celery -A worker worker --loglevel=info --pool=solo
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    restart: always

  # --- ADDED REDIS BROKER ---
  redis:
    image: redis:7-alpine
    container_name: cloud_optimizer_redis
    ports:
      - "6379:6379"
    restart: always

  beat:
    build: .
    container_name: cloud_optimizer_beat
    command: celery -A worker beat --loglevel=info
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    container_name: cloud_optimizer_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "huhuhu@123"
      POSTGRES_DB: cloud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: